# Generated by Django 2.0.7 on 2018-08-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
