# Generated by Django 2.0.7 on 2018-08-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='title',
        ),
    ]
