# Generated by Django 2.0.7 on 2018-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_remove_salary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_unit',
            field=models.CharField(choices=[('M', 'Month'), ('Y', 'Year')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
