# Generated by Django 2.0.7 on 2018-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_auto_20180801_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField()),
                ('etag', models.CharField(max_length=50)),
                ('content_length', models.IntegerField()),
                ('is_downloaded', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='modified_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='employmenttype',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='employmenttype',
            old_name='modified_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
