# Generated by Django 2.0.7 on 2018-08-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_auto_20180803_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjoblog',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
