# Generated by Django 2.0.7 on 2018-08-04 10:00

from django.db import migrations, models
import jobboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0006_auto_20180804_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(default=jobboard.models.from_now_30_days),
        ),
    ]
