# Generated by Django 2.0.7 on 2018-08-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0007_auto_20180804_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
