# Generated by Django 2.0.7 on 2018-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0009_auto_20180804_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, default='logo/default.jpg', null=True, upload_to='logo/'),
        ),
    ]
