# Generated by Django 2.0.7 on 2018-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0010_auto_20180804_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(default='logo/default.jpg', upload_to='logo/'),
        ),
    ]
