# Generated by Django 2.0.7 on 2018-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0012_auto_20180804_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
