# Generated by Django 2.0.7 on 2018-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0015_auto_20180804_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
