# Generated by Django 2.0.7 on 2018-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0016_employer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
