# Generated by Django 2.0.7 on 2018-08-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0018_auto_20180809_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
